apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rds-secrets
  namespace: atoloan-backend-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: rds-secret
  data:
  - secretKey: PGUSER
    remoteRef: {key: atoloan/postgres-prod, property: PGUSER}
  - secretKey: PGPASSWORD
    remoteRef: {key: atoloan/postgres-prod, property: PGPASSWORD}
  - secretKey: PGDATABASE
    remoteRef: {key: atoloan/postgres-prod, property: PGDATABASE}
  - secretKey: PGHOST
    remoteRef: {key: atoloan/postgres-prod, property: PGHOST}
  - secretKey: PGPORT
    remoteRef: {key: atoloan/postgres-prod, property: PGPORT}
