apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secrets
  namespace: atoloan-postgres-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: postgres-secret
  data:
  - secretKey: POSTGRES_USER
    remoteRef: {key: atoloan/postgres, property: PGUSER}
  - secretKey: POSTGRES_PASSWORD
    remoteRef: {key: atoloan/postgres, property: PGPASSWORD}
  - secretKey: POSTGRES_DB
    remoteRef: {key: atoloan/postgres, property: PGDATABASE}
